project_name: raw-manifests
release:
  github:
    owner: raz-bn
    name: kubectl-raw-manifests
builds:
  - id: raw-manifests
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/raz-bn/kubectl-raw-manifests/pkg/version.version=
archives:
  - id: raw-manifests
    builds:
    - raw-manifests
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
