apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: raw-manifests
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/raz-bn/kubectl-raw-manifests/releases/download/v0.1.0/raw-manifests_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./raw-manifests"
      to: "."
    - from: LICENSE
      to: "."
    bin: "raw-manifests"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/raz-bn/kubectl-raw-manifests/releases/download/v0.1.0/raw-manifests_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./raw-manifests"
      to: "."
    - from: LICENSE
      to: "."
    bin: "raw-manifests"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/raz-bn/kubectl-raw-manifests/releases/download/v0.1.0/raw-manifests_windows_amd64.zip
    sha256: ""
    files:
    - from: "/raw-manifests.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "raw-manifests.exe"
  shortDescription: A new plugin
  homepage: https://github.com/raz-bn/kubectl-raw-manifests
  caveats: |
    Usage:
      $ kubectl raw-manifests

    For additional options:
      $ kubectl raw-manifests --help
      or https://github.com/raz-bn/kubectl-raw-manifests/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
